// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuIAV-glrelmN-n3yRS1eqZhr3Xml27Ig',
    appId: '1:875735535485:web:19c1d72e1d77af0fdcc614',
    messagingSenderId: '875735535485',
    projectId: 'stockpulse-786',
    authDomain: 'stockpulse-786.firebaseapp.com',
    storageBucket: 'stockpulse-786.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCguOHXmZNEQDx-i8lynasWicEU4f1UGDw',
    appId: '1:875735535485:android:3c83235c87ae4296dcc614',
    messagingSenderId: '875735535485',
    projectId: 'stockpulse-786',
    storageBucket: 'stockpulse-786.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiYZVQ5eBaBEC-o9M7bJBIjXxwb3Btwt4',
    appId: '1:875735535485:ios:bdb01b2fd3f49922dcc614',
    messagingSenderId: '875735535485',
    projectId: 'stockpulse-786',
    storageBucket: 'stockpulse-786.firebasestorage.app',
    iosClientId: '875735535485-2opp6las5tn4lt6o8tvir4rq97dokhjd.apps.googleusercontent.com',
    iosBundleId: 'com.fastgen.stockpulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiYZVQ5eBaBEC-o9M7bJBIjXxwb3Btwt4',
    appId: '1:875735535485:ios:5ce4cc2e41e08b73dcc614',
    messagingSenderId: '875735535485',
    projectId: 'stockpulse-786',
    storageBucket: 'stockpulse-786.firebasestorage.app',
    iosClientId: '875735535485-56540qaernmjreb7c93ehfk1lshg7lgu.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockpulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuIAV-glrelmN-n3yRS1eqZhr3Xml27Ig',
    appId: '1:875735535485:web:f1ee1195105cadd7dcc614',
    messagingSenderId: '875735535485',
    projectId: 'stockpulse-786',
    authDomain: 'stockpulse-786.firebaseapp.com',
    storageBucket: 'stockpulse-786.firebasestorage.app',
  );
}
